name = "REALTIME @ Rutgers WINLAB"
license = "MIT"
licenselink = "https://realtime-rutgers.github.io/LICENSE.md"
description = "Home for the NSF-funded REALTIME Project at Rutgers WINLAB"
homepage = "https://realtime-rutgers.github.io/"
# demosite = "https://research-group.netlify.app/"
tags = ["academic",
        "university",
        "research",
        "publications",
        "wireless",
        "rutgers",
        "mobile edge",
        "edge cloud",
        "machine learning",
        "federated learning",
        "age of information"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Rutgers WINLAB"
  homepage = "https://winlab.rutgers.edu/"
